### ISSUE TITLE
Failure to initialize after Windows 10 Update

### ISSUE THREAD

**Issue by cgjd18** [Radeon-Pro/Max#2]
After I updated to windows 10, I would open 3ds max with a FireRender file, and I would receive an error message saying the plugin failed to initialize.  This pop up would constantly come up until Max crashes.  
I uninstalled and reinstalled the plugin with this warning popping up.   Saying the following:    Warning: Installer is not able to check your system compatibility, continue install anyway?
I don't know if you had these issues pop up on a Windows 10 Platform, but I didn't have it happen when using Windows 7.

**Comment by yozhijk** [comment]
Hi @cgjd18,

We have not noticed any issues with Win 10 on our side, however this warning means the installer could not get some system related information for some reason. We are releasing new version of the plugin shortly and we would appreciate if you could test it on your side. This version adds logging capabilities into the installer which will hopefully help us to debug in case of the problem still persist. I will let you now as soon as the new version is ready. Stay tuned!

**Comment by cgjd18** [comment]
Hi @yozhijk,

I was able to solve the problem by reinstalling the video card drivers and of the plugin itself.  So far it only recognizes 3ds max 2016, though the system has 2014 and 2017.  

Also, does the plugin support Corona material?  It seems like some do render when applied to objects.

**Comment by bstefanizzi** [comment]
Hi @cgjd18,

We will add more complete Corona support and Max 2017 plugin in the coming days. Stay tuned!

Thanks.

**Comment by yozhijk** [comment]
Hi @cgjd18 ,

We have officially moved to new repo: https://github.com/Radeon-ProRender/Max

Please use it from now on to download releases and track issues. Closing this issues since it seems to be solved.
