### ISSUE TITLE
3Ds max 2017 support

### ISSUE THREAD

**Issue by John0x** [Radeon-Pro/Max#3]
Hey, is 3ds max 2017 support planned? I really want to take fireRender for a testdrive, but I don't want to downgrade just for that.

**Comment by AshesX** [comment]
Same here. I really hope support for 3ds Max 2017 is coming soon, as the performance of FireRender was great, but since upgrading to the latest edition of 3ds Max I can no longer make use of it.

**Comment by bstefanizzi** [comment]
Hi,

Max 2017 support is coming in a few days. Stay tuned!

Thanks.

**Comment by AshesX** [comment]
Still staying tuned here. ;)

**Comment by jf4d** [comment]
Fyi Bruno
This is now supported

**Comment by jf4d** [comment]
This is now supported

**Comment by AshesX** [comment]
It would seem I missed an entire rebranding of the renderer. How confusing, but good to know moving forward. New Github page with download for those interested: https://github.com/Radeon-ProRender/max/releases

**Comment by miroslavolek** [comment]
Thanks Ashes I missed that as well >.<

**Comment by yozhijk** [comment]
Hey guys, 

The repo officially migrated to https://github.com/Radeon-ProRender/Max

Please use new repo to create issues and comment from now on. Sorry for inconvenience.
